version: 2
updates:
  - package-ecosystem: npm
    directory: /server
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
  - package-ecosystem: npm
    directory: /client
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
  - package-ecosystem: docker
    directory: /server
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /client
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: terraform
    directory: /infra/terraform
    schedule:
      interval: weekly
